# Netlify configuration file

[build]
  # Directory to publish (relative to root of your repo)
  publish = "dist/public"
  # Build command - install dependencies and build the client for Netlify
  command = "npm install && npm run build:client"
  # Ignore the server build for Netlify
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./client/"

# Redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set environment variables
[build.environment]
  NODE_ENV = "production"

# Set headers for caching and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"