# Fallback Netlify configuration in public directory
# This ensures the configuration is included in the build output

[build]
  publish = "."
  command = "# no build command needed here"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_ENV = "production"